//! W5b placeholder — mixed per-layer head_dim fixture regression.
//!
//! The fixture at ``tests/fixtures/tiny-gemma4-assistant-mixed`` uses
//! **heterogeneous** KV head_dim per layer (layer 0 = 8, layer 1 = 16),
//! mirroring Gemma-4 E2B's 256/512 split at tiny scale.  This is the
//! coverage vehicle for Sapper's blocker #4 (per-layer paged-cache geometry).
//!
//! These tests are guarded with `#[ignore]` until the per-layer paged cache
//! (W2: ``onnx-genai-kv`` + W3: ``onnx-genai-engine``) lands.  Once W3 is
//! merged, remove the `#[ignore]` attribute and confirm token-identity holds
//! across both speculative and plain-greedy paths.
//!
//! ## Fixture contents (for W5b assertions)
//!
//! Generated by `scripts/build_tiny_gemma4_assistant_mixed.py`.
//!
//! ### Target KV outputs
//!
//! | Output name         | Shape                              | head_dim |
//! |---------------------|------------------------------------|----------|
//! | `present.0.key`     | `[batch, 2, total_seq_len, 8]`     | 8        |
//! | `present.0.value`   | `[batch, 2, total_seq_len, 8]`     | 8        |
//! | `present.1.key`     | `[batch, 2, total_seq_len, 16]`    | 16       |
//! | `present.1.value`   | `[batch, 2, total_seq_len, 16]`    | 16       |
//!
//! ### Assistant shared-KV inputs
//!
//! | Input name                          | Shape                        | head_dim |
//! |-------------------------------------|------------------------------|----------|
//! | `shared_kv.sliding_attention.key`   | `[batch, 2, kv_len, 8]`      | 8        |
//! | `shared_kv.sliding_attention.value` | `[batch, 2, kv_len, 8]`      | 8        |
//! | `shared_kv.full_attention.key`      | `[batch, 2, kv_len, 16]`     | 16       |
//! | `shared_kv.full_attention.value`    | `[batch, 2, kv_len, 16]`     | 16       |
//!
//! ### Layer → group → head_dim map
//!
//! ```text
//! layer 0  →  sliding_attention  →  head_dim = 8
//! layer 1  →  full_attention     →  head_dim = 16
//! ```
//!
//! ### Fixture constants
//!
//! ```text
//! VOCAB = 32, HIDDEN = 16, KV_HEADS = 2, NUM_LAYERS = 2
//! SLIDING_HEAD_DIM = 8, FULL_HEAD_DIM = 16
//! ```

use onnx_genai_engine::{
    Engine, EngineConfig, GeneratePrompt, GenerateRequest, SharedKvBinding, SharedKvProposerConfig,
    SpeculativeMode,
};
use onnx_genai_ort::SessionOptions;
use std::path::{Path, PathBuf};

fn fixture() -> anyhow::Result<PathBuf> {
    Ok(Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/tiny-gemma4-assistant-mixed")
        .canonicalize()?)
}

fn engine(fixture: &Path, speculative_mode: SpeculativeMode) -> anyhow::Result<Engine> {
    Engine::from_dir_with_session_options(
        fixture,
        EngineConfig {
            speculative_mode,
            ..Default::default()
        },
        SessionOptions::default().with_intra_op_threads(1),
    )
}

fn assistant_config(fixture: &Path) -> SharedKvProposerConfig {
    SharedKvProposerConfig {
        assistant_model: fixture.join("assistant/model.onnx"),
        target_hidden_output: "hidden_states.0".into(),
        input_embedding_weights: fixture.join("input_embedding.f32"),
        backbone_hidden_size: 16,
        vocab_size: 32,
        num_speculative_tokens: 4,
        shared_kv: vec![
            SharedKvBinding {
                // layer 0: head_dim = 8
                name: "sliding_attention".into(),
                target_layers: vec![0],
            },
            SharedKvBinding {
                // layer 1: head_dim = 16
                name: "full_attention".into(),
                target_layers: vec![1],
            },
        ],
    }
}

fn request() -> GenerateRequest {
    let mut request = GenerateRequest::new(GeneratePrompt::Text("hello world".to_string()));
    request.options.max_new_tokens = 8;
    request.options.temperature = 0.0;
    request.options.greedy = true;
    request.options.stop_on_eos = false;
    request
}

/// W5b: speculative decoding on the mixed-head_dim fixture must be token-identical
/// to plain greedy.
///
/// Blocked on W3 per-layer paged cache landing.  The KV slicer
/// (`shared_kv_proposer_slices`) currently reads a single global head_dim from
/// `materialized.head_dim`; it must instead index the per-layer config for the
/// specific layer referenced by each `SharedKvGroup::target_layers.last()`.
///
/// When enabling: remove `#[ignore]` and confirm the test passes on CPU with the
/// existing fixture data (no fixture regeneration needed).
#[test]
#[ignore = "enable after W3 per-layer paged cache lands (see roy-gemma4-e2b-realrun-plan.md §4 W3)"]
fn gemma4_assistant_mixed_speculative_matches_plain_greedy() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut baseline = engine(&fixture, SpeculativeMode::None)?;
    let mut assistant = engine(
        &fixture,
        SpeculativeMode::SharedKv(assistant_config(&fixture)),
    )?;

    let expected = baseline.generate(request())?;
    let actual = assistant.generate(request())?;
    let stats = assistant.last_speculative_stats();

    // Layer 0: head_dim=8 (sliding_attention), Layer 1: head_dim=16 (full_attention).
    // The KV slicer must supply each group with its correct per-layer head_dim,
    // not a uniform global one, for the SharedKvInput binding to be valid.
    assert_eq!(
        actual.token_ids,
        expected.token_ids,
        "mixed head_dim: speculative output must be token-identical to plain greedy"
    );
    assert_eq!(actual.finish_reason, expected.finish_reason);
    assert!(stats.proposed_tokens > 0, "proposer was not active: {stats:?}");
    assert!(stats.verification_steps > 0, "{stats:?}");
    Ok(())
}
