//! Raw FFI bindings to ONNX Runtime C API.
//!
//! Generated by bindgen from `onnxruntime_c_api.h`.
//! Do not edit manually.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

use std::ffi::{CStr, OsString};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::sync::atomic::{AtomicBool, Ordering};

#[cfg(windows)]
type OrtGetApiBaseFn = unsafe extern "system" fn() -> *const OrtApiBase;
#[cfg(not(windows))]
type OrtGetApiBaseFn = unsafe extern "C" fn() -> *const OrtApiBase;

static REPORT_SELECTION: AtomicBool = AtomicBool::new(true);

struct OrtLibrary {
    _library: libloading::Library,
    get_api_base: OrtGetApiBaseFn,
    path: PathBuf,
    reason: String,
    version: String,
    api_version: Option<u32>,
    report_selection: bool,
}

struct LoadFailure {
    message: String,
}

enum LoadState {
    Loaded(OrtLibrary),
    Failed(LoadFailure),
}

#[derive(Clone)]
struct Candidate {
    path: PathBuf,
    reason: String,
    report_selection: bool,
}

/// Resolve ORT's process-wide C API entry point.
///
/// This intentionally replaces bindgen's link-time `OrtGetApiBase` binding. The
/// Rust binary no longer has a loader-time dependency on `onnxruntime`, which
/// lets `ONNX_GENAI_ORT_LIB` / `ONNX_GENAI_ORT_LIB_DIR` select the exact shared
/// library before the first ORT API call.
///
/// # Safety
///
/// The returned pointer is owned by ONNX Runtime and has process lifetime when
/// non-null, matching the upstream C API contract.
#[must_use]
pub unsafe fn OrtGetApiBase() -> *const OrtApiBase {
    match load_state() {
        LoadState::Loaded(loaded) => unsafe { (loaded.get_api_base)() },
        LoadState::Failed(_) => std::ptr::null(),
    }
}

#[must_use]
pub fn ort_load_error() -> Option<String> {
    match load_state() {
        LoadState::Loaded(_) => None,
        LoadState::Failed(failure) => Some(failure.message.clone()),
    }
}

#[must_use]
pub fn loaded_ort_path() -> Option<PathBuf> {
    match load_state() {
        LoadState::Loaded(loaded) => Some(loaded.path.clone()),
        LoadState::Failed(_) => None,
    }
}

#[must_use]
pub fn loaded_ort_reason() -> Option<String> {
    match load_state() {
        LoadState::Loaded(loaded) => Some(loaded.reason.clone()),
        LoadState::Failed(_) => None,
    }
}

#[must_use]
pub fn loaded_ort_version() -> Option<String> {
    match load_state() {
        LoadState::Loaded(loaded) => Some(loaded.version.clone()),
        LoadState::Failed(_) => None,
    }
}

#[must_use]
pub fn loaded_ort_api_version() -> Option<u32> {
    match load_state() {
        LoadState::Loaded(loaded) => loaded.api_version,
        LoadState::Failed(_) => None,
    }
}

pub fn set_ort_selection_report_enabled(enabled: bool) -> bool {
    REPORT_SELECTION.swap(enabled, Ordering::Relaxed)
}

fn load_state() -> &'static LoadState {
    static STATE: OnceLock<LoadState> = OnceLock::new();
    STATE.get_or_init(load_onnxruntime)
}

fn load_onnxruntime() -> LoadState {
    let config = onnx_genai_runtime_config::runtime_config();
    let mut attempts = Vec::new();
    let mut candidates = Vec::new();

    if let Some(path) = &config.ort_lib {
        let candidate = Candidate {
            path: path.clone(),
            reason: "ONNX_GENAI_ORT_LIB".to_owned(),
            report_selection: true,
        };
        return match try_load_candidate(&candidate) {
            Ok(loaded) => {
                report_loaded_library(&loaded);
                LoadState::Loaded(loaded)
            }
            Err(message) => LoadState::Failed(LoadFailure {
                message: explicit_selection_error(format!("{}: {message}", candidate.reason)),
            }),
        };
    }
    if let Some(dir) = &config.ort_lib_dir {
        let mut dir_attempts = Vec::new();
        for candidate in candidates_from_dir(dir, "ONNX_GENAI_ORT_LIB_DIR", true, true) {
            match try_load_candidate(&candidate) {
                Ok(loaded) => {
                    report_loaded_library(&loaded);
                    return LoadState::Loaded(loaded);
                }
                Err(message) => dir_attempts.push(format!("{}: {message}", candidate.reason)),
            }
        }
        return LoadState::Failed(LoadFailure {
            message: explicit_selection_error(dir_attempts.join("\n- ")),
        });
    }

    candidates.extend(auto_discovery_candidates(config));

    for candidate in candidates {
        match try_load_candidate(&candidate) {
            Ok(loaded) => {
                report_loaded_library(&loaded);
                return LoadState::Loaded(loaded);
            }
            Err(message) => {
                attempts.push(format!("{}: {message}", candidate.reason));
            }
        }
    }

    for name in default_library_names() {
        let candidate = Candidate {
            path: PathBuf::from(name),
            reason: "dynamic loader default search path".to_owned(),
            report_selection: false,
        };
        match try_load_candidate(&candidate) {
            Ok(loaded) => return LoadState::Loaded(loaded),
            Err(message) => attempts.push(format!("{}: {message}", candidate.reason)),
        }
    }

    LoadState::Failed(LoadFailure {
        message: format!(
            "Failed to load ONNX Runtime.\n\
             Attempted:\n- {}\n\
             Fix: set ONNX_GENAI_ORT_LIB to the full library path, set ONNX_GENAI_ORT_LIB_DIR \
             to a directory containing {}, activate the conda environment that contains ONNX Runtime, \
             or rebuild so ort-sys downloads ORT 1.27.0.",
            attempts.join("\n- "),
            primary_library_name()
        ),
    })
}

fn explicit_selection_error(attempts: String) -> String {
    format!(
        "Failed to load ONNX Runtime from explicit runtime selection.\n\
         Attempted:\n- {attempts}\n\
         Fix: set ONNX_GENAI_ORT_LIB to the full ONNX Runtime library file, \
         set ONNX_GENAI_ORT_LIB_DIR to its containing directory, or unset them \
         and ensure the library is discoverable through PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH."
    )
}

fn report_loaded_library(loaded: &OrtLibrary) {
    if loaded.report_selection && REPORT_SELECTION.load(Ordering::Relaxed) {
        eprintln!(
            "onnx-genai: selected ONNX Runtime {} (API {}) from {} ({})",
            loaded.version,
            loaded
                .api_version
                .map_or_else(|| "unknown".to_owned(), |v| v.to_string()),
            loaded.path.display(),
            loaded.reason
        );
    }
}

fn try_load_candidate(candidate: &Candidate) -> Result<OrtLibrary, String> {
    let library = unsafe { libloading::Library::new(&candidate.path) }
        .map_err(|err| format!("{} ({err})", candidate.path.display()))?;
    let get_api_base = unsafe {
        let symbol: libloading::Symbol<'_, OrtGetApiBaseFn> =
            library.get(b"OrtGetApiBase\0").map_err(|err| {
                format!(
                    "{} is not an ONNX Runtime library ({err})",
                    candidate.path.display()
                )
            })?;
        *symbol
    };
    let base = unsafe { get_api_base() };
    if base.is_null() {
        return Err(format!(
            "{} returned a null OrtApiBase",
            candidate.path.display()
        ));
    }
    let version = version_string(base);
    let api_version = compatible_api_version(base, &version);
    let path = resolved_candidate_path(&candidate.path, get_api_base);
    if api_version != Some(ORT_API_VERSION) {
        return Err(api_version_mismatch_message(
            &path,
            &candidate.reason,
            &version,
            api_version,
        ));
    }
    Ok(OrtLibrary {
        _library: library,
        get_api_base,
        path,
        reason: candidate.reason.clone(),
        version,
        api_version,
        report_selection: candidate.report_selection,
    })
}

fn api_version_mismatch_message(
    loaded_path: &Path,
    reason: &str,
    loaded_version: &str,
    loaded_api: Option<u32>,
) -> String {
    format!(
        "ONNX Runtime API version mismatch: loaded {} ({reason}), ORT version {}, API {}; \
         onnx-genai was built against API {} (ORT 1.27.x). \
         Fix: set ONNX_GENAI_ORT_LIB to the full path of an ORT 1.27 library, \
         set ONNX_GENAI_ORT_LIB_DIR to its containing directory, activate the conda \
         environment that contains ORT 1.27 and put its library directory first on \
         PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH, or rebuild so ort-sys downloads ORT 1.27.0.",
        loaded_path.display(),
        loaded_version,
        loaded_api.map_or_else(|| "unknown".to_owned(), |version| version.to_string()),
        ORT_API_VERSION
    )
}

fn version_string(base: *const OrtApiBase) -> String {
    unsafe {
        let Some(get_version_string) = (*base).GetVersionString else {
            return "unknown".to_owned();
        };
        let ptr = get_version_string();
        if ptr.is_null() {
            "unknown".to_owned()
        } else {
            CStr::from_ptr(ptr).to_string_lossy().into_owned()
        }
    }
}

fn compatible_api_version(base: *const OrtApiBase, version: &str) -> Option<u32> {
    unsafe {
        let get_api = (*base).GetApi?;
        if !get_api(ORT_API_VERSION).is_null() {
            return Some(ORT_API_VERSION);
        }
    }
    api_version_from_ort_version(version)
}

fn api_version_from_ort_version(version: &str) -> Option<u32> {
    let mut parts = version.split('.');
    match (parts.next(), parts.next()) {
        (Some("1"), Some(minor)) => minor.parse().ok(),
        _ => None,
    }
}

fn auto_discovery_candidates(config: &onnx_genai_runtime_config::RuntimeConfig) -> Vec<Candidate> {
    let mut candidates = Vec::new();
    if let Some(prefix) = &config.conda_prefix {
        candidates.extend(candidates_from_install_prefix(
            prefix,
            "active conda environment from CONDA_PREFIX",
        ));
    }
    if let Some(prefix) = &config.virtual_env {
        candidates.extend(candidates_from_install_prefix(
            prefix,
            "active Python virtual environment from VIRTUAL_ENV",
        ));
    }
    candidates.extend(candidates_from_target_cache());
    dedupe_candidates(candidates)
}

fn candidates_from_install_prefix(prefix: &Path, reason: &str) -> Vec<Candidate> {
    let mut dirs = Vec::new();
    if cfg!(windows) {
        dirs.push(prefix.join("Library").join("bin"));
        dirs.push(
            prefix
                .join("Lib")
                .join("site-packages")
                .join("onnxruntime")
                .join("capi"),
        );
    } else {
        dirs.push(prefix.join("lib"));
        let lib = prefix.join("lib");
        if let Ok(entries) = std::fs::read_dir(&lib) {
            for entry in entries.flatten() {
                let path = entry.path();
                let name = entry.file_name();
                if name.to_string_lossy().starts_with("python") {
                    dirs.push(path.join("site-packages").join("onnxruntime").join("capi"));
                }
            }
        }
    }
    dirs.into_iter()
        .flat_map(|dir| candidates_from_dir(&dir, reason, false, true))
        .collect()
}

fn candidates_from_target_cache() -> Vec<Candidate> {
    let mut roots = Vec::new();
    if let Ok(exe) = std::env::current_exe() {
        roots.extend(
            exe.ancestors()
                .filter(|path| path.file_name().is_some_and(|name| name == "target"))
                .map(Path::to_path_buf),
        );
    }
    if let Ok(cwd) = std::env::current_dir() {
        roots.push(cwd.join("target"));
        roots.extend(
            cwd.ancestors()
                .map(|ancestor| ancestor.join("target"))
                .filter(|path| path.exists()),
        );
    }

    let mut candidates = Vec::new();
    for root in roots {
        find_ort_prebuilt_lib_dirs(&root, &mut candidates, 0);
    }
    candidates
}

fn find_ort_prebuilt_lib_dirs(path: &Path, candidates: &mut Vec<Candidate>, depth: usize) {
    if depth > 8 || !path.is_dir() {
        return;
    }
    if path.ends_with(Path::new("ort-prebuilt").join("lib")) {
        candidates.extend(candidates_from_dir(
            path,
            "ort-sys downloaded ORT under target build output",
            false,
            true,
        ));
        return;
    }
    let Ok(entries) = std::fs::read_dir(path) else {
        return;
    };
    for entry in entries.flatten() {
        let child = entry.path();
        if !child.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if depth < 2
            || name.starts_with("onnx-genai-ort-sys-")
            || name == "out"
            || name == "ort-prebuilt"
            || name == "lib"
        {
            find_ort_prebuilt_lib_dirs(&child, candidates, depth + 1);
        }
    }
}

fn candidates_from_dir(
    dir: &Path,
    reason: &str,
    include_missing: bool,
    report_selection: bool,
) -> Vec<Candidate> {
    library_names_for_dir()
        .into_iter()
        .map(|name| dir.join(name))
        .filter(|path| include_missing || path.exists())
        .map(|path| Candidate {
            path,
            reason: reason.to_owned(),
            report_selection,
        })
        .collect()
}

fn dedupe_candidates(candidates: Vec<Candidate>) -> Vec<Candidate> {
    let mut seen = std::collections::BTreeSet::<OsString>::new();
    candidates
        .into_iter()
        .filter(|candidate| {
            let key = candidate
                .path
                .canonicalize()
                .unwrap_or_else(|_| candidate.path.clone())
                .into_os_string();
            seen.insert(key)
        })
        .collect()
}

fn primary_library_name() -> &'static str {
    if cfg!(windows) {
        "onnxruntime.dll"
    } else if cfg!(target_os = "macos") {
        "libonnxruntime.1.dylib"
    } else {
        "libonnxruntime.so.1"
    }
}

fn default_library_names() -> Vec<&'static str> {
    library_names_for_dir()
}

fn library_names_for_dir() -> Vec<&'static str> {
    if cfg!(windows) {
        vec!["onnxruntime.dll"]
    } else if cfg!(target_os = "macos") {
        vec![
            "libonnxruntime.1.dylib",
            "libonnxruntime.1.27.0.dylib",
            "libonnxruntime.dylib",
        ]
    } else {
        vec![
            "libonnxruntime.so.1",
            "libonnxruntime.so.1.27.0",
            "libonnxruntime.so",
        ]
    }
}

fn resolved_candidate_path(path: &Path, symbol: OrtGetApiBaseFn) -> PathBuf {
    if path.components().count() > 1 || path.is_absolute() {
        return path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
    }
    resolved_library_path_from_symbol(symbol as *const ()).unwrap_or_else(|| path.to_path_buf())
}

#[cfg(windows)]
fn resolved_library_path_from_symbol(symbol: *const ()) -> Option<PathBuf> {
    use std::os::windows::ffi::OsStringExt;

    const GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT: u32 = 0x0000_0002;
    const GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS: u32 = 0x0000_0004;

    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn GetModuleHandleExW(
            dwFlags: u32,
            lpModuleName: *const u16,
            phModule: *mut *mut std::ffi::c_void,
        ) -> i32;
        fn GetModuleFileNameW(
            hModule: *mut std::ffi::c_void,
            lpFilename: *mut u16,
            nSize: u32,
        ) -> u32;
    }

    unsafe {
        let mut module = std::ptr::null_mut();
        if GetModuleHandleExW(
            GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
            symbol.cast::<u16>(),
            &mut module,
        ) == 0
        {
            return None;
        }
        let mut buffer = vec![0u16; 32768];
        let len = GetModuleFileNameW(module, buffer.as_mut_ptr(), buffer.len() as u32);
        if len == 0 {
            return None;
        }
        Some(PathBuf::from(OsString::from_wide(&buffer[..len as usize])))
    }
}

#[cfg(all(unix, not(target_os = "macos")))]
#[link(name = "dl")]
unsafe extern "C" {}

#[cfg(unix)]
fn resolved_library_path_from_symbol(symbol: *const ()) -> Option<PathBuf> {
    #[repr(C)]
    struct DlInfo {
        dli_fname: *const std::ffi::c_char,
        dli_fbase: *mut std::ffi::c_void,
        dli_sname: *const std::ffi::c_char,
        dli_saddr: *mut std::ffi::c_void,
    }

    unsafe extern "C" {
        fn dladdr(addr: *const std::ffi::c_void, info: *mut DlInfo) -> i32;
    }

    unsafe {
        let mut info = DlInfo {
            dli_fname: std::ptr::null(),
            dli_fbase: std::ptr::null_mut(),
            dli_sname: std::ptr::null(),
            dli_saddr: std::ptr::null_mut(),
        };
        if dladdr(symbol.cast::<std::ffi::c_void>(), &mut info) == 0 || info.dli_fname.is_null() {
            return None;
        }
        Some(PathBuf::from(
            CStr::from_ptr(info.dli_fname)
                .to_string_lossy()
                .into_owned(),
        ))
    }
}

#[cfg(not(any(windows, unix)))]
fn resolved_library_path_from_symbol(_symbol: *const ()) -> Option<PathBuf> {
    None
}
