//! Raw FFI bindings to ONNX Runtime C API.
//!
//! Generated by bindgen from `onnxruntime_c_api.h`.
//! Do not edit manually.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
