//! Numerical-parity tests for `com.microsoft::Attention` (packed QKV) against
//! **onnxruntime 1.26.0**.
//!
//! The goldens in `msft_attention_parity/cases.rs` are generated by
//! `tests/msft_attention_parity/generate.py`, which builds a single-node
//! Attention graph per scenario, runs it through ORT's CPU EP on deterministic
//! random inputs, and records the reference outputs. This test runs the native
//! CPU kernel on the identical inputs and asserts a max-abs-diff within `1e-4`
//! (f32) — covering packed-QKV self-attention (with/without causal mask), an
//! explicit `scale`, the 1D/2D/3D `mask_index` forms, additive
//! `attention_bias`, the `past`→`present` KV cache (decode + prefill), and an
//! asymmetric `qkv_hidden_sizes` (differing V head size).
//!
//! Re-generate goldens with:
//! `python3 crates/onnx-runtime-ep-cpu/tests/msft_attention_parity/generate.py`

use onnx_runtime_ep_api::{DevicePtr, DevicePtrMut, ExecutionProvider, TensorMut, TensorView};
use onnx_runtime_ep_cpu::CpuExecutionProvider;
use onnx_runtime_ir::{Attribute, DataType, DeviceId, Node, NodeId, compute_contiguous_strides};

#[derive(Clone)]
enum InputData {
    F32(Vec<f32>),
    I32(Vec<i32>),
}

struct CaseInput {
    slot: usize,
    shape: Vec<usize>,
    data: InputData,
}

struct CaseOutput {
    shape: Vec<usize>,
    data: Vec<f32>,
}

struct Case {
    name: &'static str,
    num_heads: i64,
    scale: Option<f32>,
    mask_filter_value: Option<f32>,
    unidirectional: i64,
    qkv_hidden_sizes: Option<Vec<i64>>,
    inputs: Vec<CaseInput>,
    outputs: Vec<CaseOutput>,
}

include!("msft_attention_parity/cases.rs");

/// Backing storage for a materialized input, kept alive for the kernel call.
enum Backing {
    F32(Vec<f32>),
    I32(Vec<i32>),
}

impl Backing {
    fn dtype(&self) -> DataType {
        match self {
            Backing::F32(_) => DataType::Float32,
            Backing::I32(_) => DataType::Int32,
        }
    }
    fn ptr(&self) -> *const std::ffi::c_void {
        match self {
            Backing::F32(v) => v.as_ptr().cast(),
            Backing::I32(v) => v.as_ptr().cast(),
        }
    }
}

fn run_case(case: &Case) -> Vec<Vec<f32>> {
    // Build the kernel via the contrib-domain registration.
    let mut node = Node::new(NodeId(0), "Attention", vec![], vec![]);
    node.domain = "com.microsoft".to_string();
    node.attributes
        .insert("num_heads".into(), Attribute::Int(case.num_heads));
    if let Some(scale) = case.scale {
        node.attributes
            .insert("scale".into(), Attribute::Float(scale));
    }
    if let Some(mfv) = case.mask_filter_value {
        node.attributes
            .insert("mask_filter_value".into(), Attribute::Float(mfv));
    }
    node.attributes
        .insert("unidirectional".into(), Attribute::Int(case.unidirectional));
    if let Some(qkv) = &case.qkv_hidden_sizes {
        node.attributes
            .insert("qkv_hidden_sizes".into(), Attribute::Ints(qkv.clone()));
    }

    // Materialize inputs into positional slots, filling gaps with absent views.
    let max_slot = case.inputs.iter().map(|i| i.slot).max().unwrap_or(0);
    let n_slots = max_slot + 1;
    let mut backings: Vec<Option<Backing>> = (0..n_slots).map(|_| None).collect();
    let mut shapes: Vec<Vec<usize>> = vec![Vec::new(); n_slots];
    let mut strides: Vec<Vec<i64>> = vec![Vec::new(); n_slots];
    for input in &case.inputs {
        backings[input.slot] = Some(match &input.data {
            InputData::F32(v) => Backing::F32(v.clone()),
            InputData::I32(v) => Backing::I32(v.clone()),
        });
        shapes[input.slot] = input.shape.clone();
        strides[input.slot] = compute_contiguous_strides(&input.shape);
    }

    let input_shapes: Vec<Vec<usize>> = shapes.clone();
    let kernel = CpuExecutionProvider::new()
        .get_kernel(&node, &input_shapes, 1)
        .expect("Attention kernel should be registered");

    let views: Vec<TensorView> = (0..n_slots)
        .map(|slot| match &backings[slot] {
            Some(b) => TensorView::new(
                DevicePtr(b.ptr()),
                b.dtype(),
                &shapes[slot],
                &strides[slot],
                DeviceId::cpu(),
            ),
            None => TensorView::absent(DataType::Float32),
        })
        .collect();

    // Allocate output buffers matching the ORT golden shapes.
    let mut out_storage: Vec<Vec<f32>> = case
        .outputs
        .iter()
        .map(|o| vec![0.0f32; o.shape.iter().product()])
        .collect();
    let out_strides: Vec<Vec<i64>> = case
        .outputs
        .iter()
        .map(|o| compute_contiguous_strides(&o.shape))
        .collect();
    let mut out_views: Vec<TensorMut> = out_storage
        .iter_mut()
        .zip(case.outputs.iter())
        .zip(out_strides.iter())
        .map(|((buf, o), st)| {
            TensorMut::new(
                DevicePtrMut(buf.as_mut_ptr().cast()),
                DataType::Float32,
                &o.shape,
                st,
                DeviceId::cpu(),
            )
        })
        .collect();

    kernel
        .execute(&views, &mut out_views)
        .unwrap_or_else(|e| panic!("case {}: kernel failed: {e:?}", case.name));

    out_storage
}

#[test]
fn msft_attention_matches_onnxruntime_1_26_0() {
    const TOL: f32 = 1e-4;
    let cases = cases();
    let mut summary = Vec::new();
    for case in &cases {
        let got = run_case(case);
        assert_eq!(
            got.len(),
            case.outputs.len(),
            "case {}: output count mismatch",
            case.name
        );
        let mut case_max = 0.0f32;
        for (idx, (actual, expected)) in got.iter().zip(case.outputs.iter()).enumerate() {
            assert_eq!(
                actual.len(),
                expected.data.len(),
                "case {} output {idx}: length mismatch",
                case.name
            );
            let mut max_diff = 0.0f32;
            for (a, e) in actual.iter().zip(expected.data.iter()) {
                max_diff = max_diff.max((a - e).abs());
            }
            case_max = case_max.max(max_diff);
            assert!(
                max_diff <= TOL,
                "case {} output {idx}: max abs diff {max_diff:e} exceeds {TOL:e}",
                case.name
            );
        }
        summary.push((case.name, case_max));
    }
    // Surface the per-scenario parity margin (visible with `--nocapture`).
    for (name, max_diff) in &summary {
        println!("[msft-attention-parity] {name}: max abs diff {max_diff:e}");
    }
}
