//! Raw FFI bindings to pytorch/cpuinfo.
//!
//! Auto-generated by bindgen. Do not edit.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/cpuinfo_bindings.rs"));
