//! End-to-end conformance test: run the `bert_toy_optimized` model through the
//! full session stack (loader -> IR -> CPU EP -> executor) and compare both
//! outputs against a committed onnxruntime CPU reference.
//!
//! This is the Phase-1 EXIT MILESTONE: the first full-stack run of a real ONNX
//! model. The fixtures under `tests/fixtures/bert_toy/` are generated by
//! `gen_reference.py` (onnxruntime 1.27.0, CPUExecutionProvider) and committed,
//! so this test is self-contained and needs no Python at test time.
//!
//! Nothing here special-cases "bert" in library code — the model is purely a
//! test fixture. The executor is exercised as a generic Graph runner.

use std::path::{Path, PathBuf};

use onnx_runtime_session::{InferenceSession, Tensor};

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/bert_toy")
}

fn read_bin(name: &str) -> Vec<u8> {
    let path = fixture_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read fixture {}: {e}", path.display()))
}

fn i64_input(name: &str) -> Tensor {
    // All model inputs are int64 [1, 8] (see manifest.json).
    let bytes = read_bin(name);
    let data: Vec<i64> = bytes
        .chunks_exact(8)
        .map(|c| i64::from_le_bytes(c.try_into().unwrap()))
        .collect();
    assert_eq!(data.len(), 8, "{name} expected 8 int64 values");
    Tensor::from_i64(&[1, 8], &data).unwrap()
}

fn f32_reference(name: &str) -> Vec<f32> {
    read_bin(name)
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

/// Compare `actual` against `reference`, returning (max_abs_err, max_rel_err).
fn compare(actual: &[f32], reference: &[f32]) -> (f32, f32) {
    assert_eq!(
        actual.len(),
        reference.len(),
        "output element count mismatch (got {}, expected {})",
        actual.len(),
        reference.len()
    );
    let mut max_abs = 0.0f32;
    let mut max_rel = 0.0f32;
    for (&a, &r) in actual.iter().zip(reference.iter()) {
        let abs = (a - r).abs();
        max_abs = max_abs.max(abs);
        let rel = abs / (r.abs() + 1e-6);
        max_rel = max_rel.max(rel);
    }
    (max_abs, max_rel)
}

#[test]
fn bert_toy_matches_onnxruntime_cpu() {
    // Tolerance: our naive CPU kernels + Abramowitz-&-Stegun `Erf` differ from
    // ORT's optimized/fused kernels in accumulation order, so bit-exactness is
    // not expected. `atol = rtol = 2e-3` comfortably covers the observed error
    // on this ~384-node BERT graph; a value's error passes if it is within EITHER
    // the absolute OR the relative bound (standard `numpy.allclose` semantics).
    const ATOL: f32 = 2e-3;
    const RTOL: f32 = 2e-3;

    let model_path = fixture_dir().join("model.onnx");
    let mut session = InferenceSession::load(&model_path)
        .unwrap_or_else(|e| panic!("load {}: {e}", model_path.display()));

    let input_ids = i64_input("input_ids.bin");
    let token_type_ids = i64_input("token_type_ids.bin");
    let input_mask = i64_input("input_mask.bin");

    let outputs = session
        .run(&[
            ("input_ids", &input_ids),
            ("token_type_ids", &token_type_ids),
            ("input_mask", &input_mask),
        ])
        .expect("run bert_toy inference");

    // Outputs are returned in graph order: prediction_scores, then
    // seq_relationship_score (see manifest.json).
    assert_eq!(outputs.len(), 2, "expected 2 model outputs");

    let cases: [(&str, &str, &[usize]); 2] = [
        ("prediction_scores", "prediction_scores.bin", &[1, 8, 99]),
        ("seq_relationship_score", "seq_relationship_score.bin", &[1, 2]),
    ];

    let mut overall_max_abs = 0.0f32;
    let mut overall_max_rel = 0.0f32;

    for (i, (label, bin, shape)) in cases.iter().enumerate() {
        let out = &outputs[i];
        assert_eq!(
            &out.shape, shape,
            "{label}: shape mismatch (got {:?}, expected {shape:?})",
            out.shape
        );
        let actual = out.to_vec_f32();
        let reference = f32_reference(bin);
        let (max_abs, max_rel) = compare(&actual, &reference);
        overall_max_abs = overall_max_abs.max(max_abs);
        overall_max_rel = overall_max_rel.max(max_rel);

        eprintln!("{label}: max_abs_err = {max_abs:.3e}, max_rel_err = {max_rel:.3e}");

        // Count elements exceeding BOTH bounds (a genuine failure per allclose).
        let n_fail = actual
            .iter()
            .zip(reference.iter())
            .filter(|&(&a, &r)| (a - r).abs() > ATOL + RTOL * r.abs())
            .count();
        assert_eq!(
            n_fail, 0,
            "{label}: {n_fail}/{} elements exceed atol={ATOL:.0e} + rtol={RTOL:.0e}; \
             max_abs={max_abs:.3e}, max_rel={max_rel:.3e}",
            actual.len()
        );
    }

    eprintln!(
        "bert_toy conformance PASS: overall max_abs_err = {overall_max_abs:.3e}, \
         overall max_rel_err = {overall_max_rel:.3e}"
    );
}
