#!/usr/bin/env python3
"""Generate small VLM preprocessing references from pinned HF processors."""

from pathlib import Path

import numpy as np
from PIL import Image
from transformers import AutoImageProcessor
from transformers.image_utils import ChannelDimension


QWEN_MODEL = "Qwen/Qwen3-VL-2B-Instruct"
QWEN_REVISION = "89644892e4d85e24eaac8bacfd4f463576704203"
PHI_MODEL = "microsoft/Phi-3-vision-128k-instruct"
PHI_REVISION = "ed2772fabe9dc9acd0caad54b62761d92520cc44"


def patterned_image(width: int, height: int, multiplier: int, offset: int) -> np.ndarray:
    values = (np.arange(width * height * 3, dtype=np.uint16) * multiplier + offset) % 256
    return values.astype(np.uint8).reshape(height, width, 3)


def patchify_chw(image: np.ndarray, patch_size: int) -> np.ndarray:
    channels, height, width = image.shape
    patches = []
    for patch_y in range(height // patch_size):
        for patch_x in range(width // patch_size):
            patch = image[
                :,
                patch_y * patch_size : (patch_y + 1) * patch_size,
                patch_x * patch_size : (patch_x + 1) * patch_size,
            ]
            patches.append(patch.reshape(channels * patch_size * patch_size))
    return np.stack(patches)


def bf16_bits(values: np.ndarray) -> np.ndarray:
    bits = values.astype(np.float32).view(np.uint32)
    bias = np.uint32(0x7FFF) + ((bits >> np.uint32(16)) & np.uint32(1))
    return ((bits + bias) >> np.uint32(16)).astype(np.uint16)


def rust_array(name: str, rust_type: str, values: np.ndarray) -> str:
    flat = values.reshape(-1)
    if rust_type == "u32":
        rendered = ", ".join(f"0x{int(value):08x}" for value in flat)
    elif rust_type == "u16":
        rendered = ", ".join(f"0x{int(value):04x}" for value in flat)
    else:
        rendered = ", ".join(str(int(value)) for value in flat)
    return f"pub const {name}: [{rust_type}; {flat.size}] = [{rendered}];\n"


def main() -> None:
    qwen = AutoImageProcessor.from_pretrained(QWEN_MODEL, revision=QWEN_REVISION)
    qwen_images = [
        patterned_image(4, 4, 1, 0),
        patterned_image(4, 4, 5, 17),
    ]
    qwen_output = qwen(
        images=[Image.fromarray(image, "RGB") for image in qwen_images],
        do_resize=False,
        do_rescale=True,
        do_normalize=False,
        patch_size=2,
        temporal_patch_size=1,
        merge_size=1,
        return_tensors="np",
    )
    qwen_pixels = np.asarray(qwen_output["pixel_values"], dtype=np.float32)
    qwen_grid = np.asarray(qwen_output["image_grid_thw"], dtype=np.int64)

    phi = AutoImageProcessor.from_pretrained(
        PHI_MODEL,
        revision=PHI_REVISION,
        trust_remote_code=True,
    )
    phi_images = [
        patterned_image(8, 4, 3, 11),
        patterned_image(4, 4, 7, 23),
    ]
    phi_tiles = [phi_images[0][:, :4], phi_images[0][:, 4:], phi_images[1]]
    phi_patches = []
    for tile in phi_tiles:
        scaled = phi.rescale(
            tile,
            scale=1 / 255,
            input_data_format=ChannelDimension.LAST,
        )
        normalized = phi.normalize(
            scaled,
            mean=phi.image_mean,
            std=phi.image_std,
            input_data_format=ChannelDimension.LAST,
            data_format=ChannelDimension.FIRST,
        )
        phi_patches.append(patchify_chw(np.asarray(normalized, dtype=np.float32), 2))
    first = np.concatenate(phi_patches[:2])
    second = phi_patches[2]
    phi_pixels = np.zeros((2, first.shape[0], first.shape[1]), dtype=np.float32)
    phi_pixels[0, : first.shape[0]] = first
    phi_pixels[1, : second.shape[0]] = second
    phi_sizes = np.asarray([[4, 8], [4, 4]], dtype=np.int64)
    phi_mask = np.asarray([[1] * 8, [1] * 4 + [0] * 4], dtype=np.uint8)

    output = [
        "// Generated by generate_hf_vlm_reference.py from pinned real HF processors.\n",
        rust_array("QWEN_IMAGE_0", "u8", qwen_images[0]),
        rust_array("QWEN_IMAGE_1", "u8", qwen_images[1]),
        rust_array("QWEN_PIXEL_BITS", "u32", qwen_pixels.view(np.uint32)),
        rust_array("QWEN_GRID", "i64", qwen_grid),
        rust_array("PHI_IMAGE_0", "u8", phi_images[0]),
        rust_array("PHI_IMAGE_1", "u8", phi_images[1]),
        rust_array("PHI_FP16_BITS", "u16", phi_pixels.astype(np.float16).view(np.uint16)),
        rust_array("PHI_BF16_BITS", "u16", bf16_bits(phi_pixels)),
        rust_array("PHI_SIZES", "i64", phi_sizes),
        rust_array("PHI_MASK", "u8", phi_mask),
    ]
    Path(__file__).with_name("hf_vlm_reference.rs").write_text("".join(output))


if __name__ == "__main__":
    main()
