//! CUDA-gated lifecycle test for the uncaptured persistent decode path.
//!
//! Shared-KV models that cannot capture a CUDA graph (top-level control-flow
//! ops, e.g. Phi-4-mini's long-context RoPE `If`) run through
//! `DecodeSession::step_persistent` with `use_graph == false`. That path reuses
//! the captured path's persistent fixed-address I/O machinery but must NEVER
//! claim a CUDA-graph annotation id — otherwise it would leak an id it never
//! captures under and could release a graph that does not exist.
//!
//! This asserts that invariant on real hardware across the full decode
//! lifecycle: prefill, decode steps, `reset()` (which calls
//! `invalidate_captured_graph`), and post-reset decode. It is skipped (not
//! failed) when no CUDA device is active, so it is safe in CPU-only CI.
//!
//! The fixture is a tiny fp16 GQA shared-buffer decoder generated by
//! `tests/fixtures/tiny-llm-shared-kv/generate_tiny_shared_kv.py`.
#![cfg(feature = "cuda")]

use std::path::{Path, PathBuf};
use std::sync::{Mutex, OnceLock};

use onnx_genai_ort::{
    DecodeSession, DecodeSessionOptions, Environment, Session, SessionOptions, ep_selection,
};

const MAX_LENGTH: usize = 16;

fn shared_kv_model() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures/tiny-llm-shared-kv/model.onnx")
}

fn test_environment() -> &'static Environment {
    static ENVIRONMENT: OnceLock<Environment> = OnceLock::new();
    ENVIRONMENT.get_or_init(|| Environment::new("uncaptured-persistent-decode-test").expect("env"))
}

fn ort_test_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

/// Build the fixture session on CUDA, or return `None` to skip when no CUDA
/// device is active (the EP silently falls back to CPU, where the persistent
/// path does not apply).
fn cuda_shared_kv_session() -> Option<Session> {
    let options = SessionOptions::with_execution_provider(ep_selection("cuda"));
    let session = match Session::new(test_environment(), &shared_kv_model(), options) {
        Ok(session) => session,
        Err(error) => {
            eprintln!("skipping: could not build CUDA session: {error}");
            return None;
        }
    };
    if session.cuda_device_id().is_none() {
        eprintln!("skipping: no active CUDA device (EP fell back to host)");
        return None;
    }
    Some(session)
}

fn shared_buffer_decode(session: &Session) -> DecodeSession<'_> {
    DecodeSession::new(
        session,
        DecodeSessionOptions {
            batch_size: 1,
            max_length: Some(MAX_LENGTH),
            // The fixture is a GQA shared-buffer model; opt in explicitly (the
            // engine does the same for these models).
            past_present_share_buffer: Some(true),
        },
    )
    .expect("shared-buffer decode session")
}

#[test]
fn uncaptured_shared_buffer_decode_never_claims_a_graph_id() {
    let _guard = ort_test_lock().lock().unwrap_or_else(|poison| poison.into_inner());

    let Some(session) = cuda_shared_kv_session() else {
        return;
    };

    // A control-flow / uncaptured model runs without graph capture: the session
    // must report `graph_capture() == false`, which is what routes decode
    // through the persistent (uncaptured) path rather than the captured graph.
    assert!(
        !session.graph_capture(),
        "fixture session must be uncaptured for this test to exercise the persistent path"
    );

    let mut decode = shared_buffer_decode(&session);
    assert_eq!(
        decode.capture_graph_id_for_test(),
        None,
        "a fresh uncaptured session holds no graph id"
    );

    // Prefill (multi-token) — routed through the standard path (current_len==0),
    // must not claim a graph id.
    let prompt = [2_i64, 4, 5]; // <bos> hello world
    let prompt_mask = vec![1_i64; prompt.len()];
    let prompt_pos = (0..prompt.len() as i64).collect::<Vec<_>>();
    decode
        .step(&prompt, &prompt_mask, &prompt_pos)
        .expect("prefill step");
    assert_eq!(
        decode.capture_graph_id_for_test(),
        None,
        "prefill must not claim a graph id"
    );

    // Single-token decode steps — these hit `step_persistent(use_graph=false)`.
    for offset in 0..4 {
        let total = prompt.len() + offset + 1;
        let position = (prompt.len() + offset) as i64;
        decode
            .step(&[6_i64], &vec![1_i64; total], &[position])
            .expect("uncaptured decode step");
        assert_eq!(
            decode.capture_graph_id_for_test(),
            None,
            "uncaptured decode step {offset} must not claim a graph id"
        );
    }

    // `reset()` calls `invalidate_captured_graph()`. For an uncaptured session
    // that must leave the id `None` (no graph to release, no fresh id acquired).
    decode.reset();
    assert_eq!(
        decode.capture_graph_id_for_test(),
        None,
        "reset must leave an uncaptured session with no graph id"
    );

    // Decode again after reset — still no id.
    decode
        .step(&prompt, &prompt_mask, &prompt_pos)
        .expect("post-reset prefill");
    decode
        .step(&[6_i64], &vec![1_i64; prompt.len() + 1], &[prompt.len() as i64])
        .expect("post-reset decode step");
    assert_eq!(
        decode.capture_graph_id_for_test(),
        None,
        "post-reset uncaptured decode must not claim a graph id"
    );
}
