// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod onnxruntime {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};
    #[allow(unused_imports, dead_code)]
    pub mod adapters {

        use core::cmp::Ordering;
        use core::mem;

        extern crate flatbuffers;
        use self::flatbuffers::{EndianScalar, Follow};

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_TENSOR_DATA_TYPE: i32 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_TENSOR_DATA_TYPE: i32 = 20;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_TENSOR_DATA_TYPE: [TensorDataType; 21] = [
            TensorDataType::UNDEFINED,
            TensorDataType::FLOAT,
            TensorDataType::UINT8,
            TensorDataType::INT8,
            TensorDataType::UINT16,
            TensorDataType::INT16,
            TensorDataType::INT32,
            TensorDataType::INT64,
            TensorDataType::STRING,
            TensorDataType::BOOL,
            TensorDataType::FLOAT16,
            TensorDataType::DOUBLE,
            TensorDataType::UINT32,
            TensorDataType::UINT64,
            TensorDataType::COMPLEX64,
            TensorDataType::COMPLEX128,
            TensorDataType::BFLOAT16,
            TensorDataType::FLOAT8E4M3FN,
            TensorDataType::FLOAT8E4M3FNUZ,
            TensorDataType::FLOAT8E5M2,
            TensorDataType::FLOAT8E5M2FNUZ,
        ];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct TensorDataType(pub i32);
        #[allow(non_upper_case_globals)]
        impl TensorDataType {
            pub const UNDEFINED: Self = Self(0);
            pub const FLOAT: Self = Self(1);
            pub const UINT8: Self = Self(2);
            pub const INT8: Self = Self(3);
            pub const UINT16: Self = Self(4);
            pub const INT16: Self = Self(5);
            pub const INT32: Self = Self(6);
            pub const INT64: Self = Self(7);
            pub const STRING: Self = Self(8);
            pub const BOOL: Self = Self(9);
            pub const FLOAT16: Self = Self(10);
            pub const DOUBLE: Self = Self(11);
            pub const UINT32: Self = Self(12);
            pub const UINT64: Self = Self(13);
            pub const COMPLEX64: Self = Self(14);
            pub const COMPLEX128: Self = Self(15);
            pub const BFLOAT16: Self = Self(16);
            pub const FLOAT8E4M3FN: Self = Self(17);
            pub const FLOAT8E4M3FNUZ: Self = Self(18);
            pub const FLOAT8E5M2: Self = Self(19);
            pub const FLOAT8E5M2FNUZ: Self = Self(20);

            pub const ENUM_MIN: i32 = 0;
            pub const ENUM_MAX: i32 = 20;
            pub const ENUM_VALUES: &'static [Self] = &[
                Self::UNDEFINED,
                Self::FLOAT,
                Self::UINT8,
                Self::INT8,
                Self::UINT16,
                Self::INT16,
                Self::INT32,
                Self::INT64,
                Self::STRING,
                Self::BOOL,
                Self::FLOAT16,
                Self::DOUBLE,
                Self::UINT32,
                Self::UINT64,
                Self::COMPLEX64,
                Self::COMPLEX128,
                Self::BFLOAT16,
                Self::FLOAT8E4M3FN,
                Self::FLOAT8E4M3FNUZ,
                Self::FLOAT8E5M2,
                Self::FLOAT8E5M2FNUZ,
            ];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::UNDEFINED => Some("UNDEFINED"),
                    Self::FLOAT => Some("FLOAT"),
                    Self::UINT8 => Some("UINT8"),
                    Self::INT8 => Some("INT8"),
                    Self::UINT16 => Some("UINT16"),
                    Self::INT16 => Some("INT16"),
                    Self::INT32 => Some("INT32"),
                    Self::INT64 => Some("INT64"),
                    Self::STRING => Some("STRING"),
                    Self::BOOL => Some("BOOL"),
                    Self::FLOAT16 => Some("FLOAT16"),
                    Self::DOUBLE => Some("DOUBLE"),
                    Self::UINT32 => Some("UINT32"),
                    Self::UINT64 => Some("UINT64"),
                    Self::COMPLEX64 => Some("COMPLEX64"),
                    Self::COMPLEX128 => Some("COMPLEX128"),
                    Self::BFLOAT16 => Some("BFLOAT16"),
                    Self::FLOAT8E4M3FN => Some("FLOAT8E4M3FN"),
                    Self::FLOAT8E4M3FNUZ => Some("FLOAT8E4M3FNUZ"),
                    Self::FLOAT8E5M2 => Some("FLOAT8E5M2"),
                    Self::FLOAT8E5M2FNUZ => Some("FLOAT8E5M2FNUZ"),
                    _ => None,
                }
            }
        }
        impl core::fmt::Debug for TensorDataType {
            fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> flatbuffers::Follow<'a> for TensorDataType {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = flatbuffers::read_scalar_at::<i32>(buf, loc);
                Self(b)
            }
        }

        impl flatbuffers::Push for TensorDataType {
            type Output = TensorDataType;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                flatbuffers::emplace_scalar::<i32>(dst, self.0);
            }
        }

        impl flatbuffers::EndianScalar for TensorDataType {
            type Scalar = i32;
            #[inline]
            fn to_little_endian(self) -> i32 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: i32) -> Self {
                let b = i32::from_le(v);
                Self(b)
            }
        }

        impl<'a> flatbuffers::Verifiable for TensorDataType {
            #[inline]
            fn run_verifier(
                v: &mut flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
                use self::flatbuffers::Verifiable;
                i32::run_verifier(v, pos)
            }
        }

        impl flatbuffers::SimpleToVerifyInSlice for TensorDataType {}
        pub enum ParameterOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Parameter<'a> {
            pub _tab: flatbuffers::Table<'a>,
        }

        impl<'a> flatbuffers::Follow<'a> for Parameter<'a> {
            type Inner = Parameter<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: flatbuffers::Table::new(buf, loc),
                }
            }
        }

        impl<'a> Parameter<'a> {
            pub const VT_NAME: flatbuffers::VOffsetT = 4;
            pub const VT_DIMS: flatbuffers::VOffsetT = 6;
            pub const VT_DATA_TYPE: flatbuffers::VOffsetT = 8;
            pub const VT_RAW_DATA: flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
                Parameter { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args ParameterArgs<'args>,
            ) -> flatbuffers::WIPOffset<Parameter<'bldr>> {
                let mut builder = ParameterBuilder::new(_fbb);
                if let Some(x) = args.raw_data {
                    builder.add_raw_data(x);
                }
                builder.add_data_type(args.data_type);
                if let Some(x) = args.dims {
                    builder.add_dims(x);
                }
                if let Some(x) = args.name {
                    builder.add_name(x);
                }
                builder.finish()
            }

            #[inline]
            pub fn name(&self) -> Option<&'a str> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<flatbuffers::ForwardsUOffset<&str>>(Parameter::VT_NAME, None)
                }
            }
            #[inline]
            pub fn dims(&self) -> Option<flatbuffers::Vector<'a, i64>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i64>>>(
                            Parameter::VT_DIMS,
                            None,
                        )
                }
            }
            #[inline]
            pub fn data_type(&self) -> TensorDataType {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<TensorDataType>(
                            Parameter::VT_DATA_TYPE,
                            Some(TensorDataType::UNDEFINED),
                        )
                        .unwrap()
                }
            }
            #[inline]
            pub fn raw_data(&self) -> Option<flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                            Parameter::VT_RAW_DATA,
                            None,
                        )
                }
            }
        }

        impl flatbuffers::Verifiable for Parameter<'_> {
            #[inline]
            fn run_verifier(
                v: &mut flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
                use self::flatbuffers::Verifiable;
                v.visit_table(pos)?
                    .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                        "name",
                        Self::VT_NAME,
                        false,
                    )?
                    .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i64>>>(
                        "dims",
                        Self::VT_DIMS,
                        false,
                    )?
                    .visit_field::<TensorDataType>("data_type", Self::VT_DATA_TYPE, false)?
                    .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                        "raw_data",
                        Self::VT_RAW_DATA,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct ParameterArgs<'a> {
            pub name: Option<flatbuffers::WIPOffset<&'a str>>,
            pub dims: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i64>>>,
            pub data_type: TensorDataType,
            pub raw_data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
        }
        impl<'a> Default for ParameterArgs<'a> {
            #[inline]
            fn default() -> Self {
                ParameterArgs {
                    name: None,
                    dims: None,
                    data_type: TensorDataType::UNDEFINED,
                    raw_data: None,
                }
            }
        }

        pub struct ParameterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
            fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ParameterBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b str>) {
                self.fbb_
                    .push_slot_always::<flatbuffers::WIPOffset<_>>(Parameter::VT_NAME, name);
            }
            #[inline]
            pub fn add_dims(&mut self, dims: flatbuffers::WIPOffset<flatbuffers::Vector<'b, i64>>) {
                self.fbb_
                    .push_slot_always::<flatbuffers::WIPOffset<_>>(Parameter::VT_DIMS, dims);
            }
            #[inline]
            pub fn add_data_type(&mut self, data_type: TensorDataType) {
                self.fbb_.push_slot::<TensorDataType>(
                    Parameter::VT_DATA_TYPE,
                    data_type,
                    TensorDataType::UNDEFINED,
                );
            }
            #[inline]
            pub fn add_raw_data(
                &mut self,
                raw_data: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                    Parameter::VT_RAW_DATA,
                    raw_data,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> ParameterBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                ParameterBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> flatbuffers::WIPOffset<Parameter<'a>> {
                let o = self.fbb_.end_table(self.start_);
                flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl core::fmt::Debug for Parameter<'_> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                let mut ds = f.debug_struct("Parameter");
                ds.field("name", &self.name());
                ds.field("dims", &self.dims());
                ds.field("data_type", &self.data_type());
                ds.field("raw_data", &self.raw_data());
                ds.finish()
            }
        }
        pub enum AdapterOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct Adapter<'a> {
            pub _tab: flatbuffers::Table<'a>,
        }

        impl<'a> flatbuffers::Follow<'a> for Adapter<'a> {
            type Inner = Adapter<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: flatbuffers::Table::new(buf, loc),
                }
            }
        }

        impl<'a> Adapter<'a> {
            pub const VT_FORMAT_VERSION: flatbuffers::VOffsetT = 4;
            pub const VT_ADAPTER_VERSION: flatbuffers::VOffsetT = 6;
            pub const VT_MODEL_VERSION: flatbuffers::VOffsetT = 8;
            pub const VT_PARAMETERS: flatbuffers::VOffsetT = 10;

            #[inline]
            pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
                Adapter { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args AdapterArgs<'args>,
            ) -> flatbuffers::WIPOffset<Adapter<'bldr>> {
                let mut builder = AdapterBuilder::new(_fbb);
                if let Some(x) = args.parameters {
                    builder.add_parameters(x);
                }
                builder.add_model_version(args.model_version);
                builder.add_adapter_version(args.adapter_version);
                builder.add_format_version(args.format_version);
                builder.finish()
            }

            #[inline]
            pub fn format_version(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(Adapter::VT_FORMAT_VERSION, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn adapter_version(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(Adapter::VT_ADAPTER_VERSION, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn model_version(&self) -> i32 {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<i32>(Adapter::VT_MODEL_VERSION, Some(0))
                        .unwrap()
                }
            }
            #[inline]
            pub fn parameters(
                &self,
            ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Parameter<'a>>>>
            {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab.get::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Parameter>>,
                    >>(Adapter::VT_PARAMETERS, None)
                }
            }
        }

        impl flatbuffers::Verifiable for Adapter<'_> {
            #[inline]
            fn run_verifier(
                v: &mut flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
                use self::flatbuffers::Verifiable;
                v.visit_table(pos)?
                    .visit_field::<i32>("format_version", Self::VT_FORMAT_VERSION, false)?
                    .visit_field::<i32>("adapter_version", Self::VT_ADAPTER_VERSION, false)?
                    .visit_field::<i32>("model_version", Self::VT_MODEL_VERSION, false)?
                    .visit_field::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Parameter>>,
                    >>("parameters", Self::VT_PARAMETERS, false)?
                    .finish();
                Ok(())
            }
        }
        pub struct AdapterArgs<'a> {
            pub format_version: i32,
            pub adapter_version: i32,
            pub model_version: i32,
            pub parameters: Option<
                flatbuffers::WIPOffset<
                    flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Parameter<'a>>>,
                >,
            >,
        }
        impl<'a> Default for AdapterArgs<'a> {
            #[inline]
            fn default() -> Self {
                AdapterArgs {
                    format_version: 0,
                    adapter_version: 0,
                    model_version: 0,
                    parameters: None,
                }
            }
        }

        pub struct AdapterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
            fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> AdapterBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_format_version(&mut self, format_version: i32) {
                self.fbb_
                    .push_slot::<i32>(Adapter::VT_FORMAT_VERSION, format_version, 0);
            }
            #[inline]
            pub fn add_adapter_version(&mut self, adapter_version: i32) {
                self.fbb_
                    .push_slot::<i32>(Adapter::VT_ADAPTER_VERSION, adapter_version, 0);
            }
            #[inline]
            pub fn add_model_version(&mut self, model_version: i32) {
                self.fbb_
                    .push_slot::<i32>(Adapter::VT_MODEL_VERSION, model_version, 0);
            }
            #[inline]
            pub fn add_parameters(
                &mut self,
                parameters: flatbuffers::WIPOffset<
                    flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<Parameter<'b>>>,
                >,
            ) {
                self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                    Adapter::VT_PARAMETERS,
                    parameters,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> AdapterBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                AdapterBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> flatbuffers::WIPOffset<Adapter<'a>> {
                let o = self.fbb_.end_table(self.start_);
                flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl core::fmt::Debug for Adapter<'_> {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                let mut ds = f.debug_struct("Adapter");
                ds.field("format_version", &self.format_version());
                ds.field("adapter_version", &self.adapter_version());
                ds.field("model_version", &self.model_version());
                ds.field("parameters", &self.parameters());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `Adapter`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_adapter_unchecked`.
        pub fn root_as_adapter(buf: &[u8]) -> Result<Adapter, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::root::<Adapter>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `Adapter` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_adapter_unchecked`.
        pub fn size_prefixed_root_as_adapter(
            buf: &[u8],
        ) -> Result<Adapter, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::size_prefixed_root::<Adapter>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `Adapter` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_adapter_unchecked`.
        pub fn root_as_adapter_with_opts<'b, 'o>(
            opts: &'o flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Adapter<'b>, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::root_with_opts::<Adapter<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `Adapter` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_adapter_unchecked`.
        pub fn size_prefixed_root_as_adapter_with_opts<'b, 'o>(
            opts: &'o flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<Adapter<'b>, flatbuffers::InvalidFlatbuffer> {
            flatbuffers::size_prefixed_root_with_opts::<Adapter<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a Adapter and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `Adapter`.
        pub unsafe fn root_as_adapter_unchecked(buf: &[u8]) -> Adapter {
            flatbuffers::root_unchecked::<Adapter>(buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed Adapter and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `Adapter`.
        pub unsafe fn size_prefixed_root_as_adapter_unchecked(buf: &[u8]) -> Adapter {
            flatbuffers::size_prefixed_root_unchecked::<Adapter>(buf)
        }
        pub const ADAPTER_IDENTIFIER: &str = "TORT";

        #[inline]
        pub fn adapter_buffer_has_identifier(buf: &[u8]) -> bool {
            flatbuffers::buffer_has_identifier(buf, ADAPTER_IDENTIFIER, false)
        }

        #[inline]
        pub fn adapter_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
            flatbuffers::buffer_has_identifier(buf, ADAPTER_IDENTIFIER, true)
        }

        #[inline]
        pub fn finish_adapter_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            root: flatbuffers::WIPOffset<Adapter<'a>>,
        ) {
            fbb.finish(root, Some(ADAPTER_IDENTIFIER));
        }

        #[inline]
        pub fn finish_size_prefixed_adapter_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
            fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
            root: flatbuffers::WIPOffset<Adapter<'a>>,
        ) {
            fbb.finish_size_prefixed(root, Some(ADAPTER_IDENTIFIER));
        }
    } // pub mod adapters
} // pub mod onnxruntime
